### ISSUE TITLE
may I ask what software do you use for your interface? 

### ISSUE THREAD

**Issue by ghost** [Bugswriter/dotfiles#2]
for example, what window manager do you use? what terminal emulator? what status bar, shell or filemanager?

**Comment by dazrik** [comment]
He uses dwm (window manager), st (terminal emulator), dwm_bar (status bar), zsh (shell).
I may be wrong, but I hope I could help.

**Comment by ghost** [comment]
Thunar(GUI file manager) and Ranger(CLI file manager)
I think he hates using file managers though
https://youtu.be/4CIlA9WXpn0
https://youtu.be/_xxTcKJMnWQ
